ERROR - 2021-04-22 16:59:29 --> Error connecting to the database: Unknown database 'taskapp'
CRITICAL - 2021-04-22 16:59:29 --> Unable to connect to the database.
#0 C:\xampp\htdocs\hello-world\vendor\codeigniter4\framework\system\Database\BaseConnection.php(618): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\hello-world\app\Models\TaskModel.php(16): CodeIgniter\Database\BaseConnection->query('SELECT * FROM t...')
#2 C:\xampp\htdocs\hello-world\app\Controllers\TaskController.php(10): App\Models\TaskModel->readTasks()
#3 C:\xampp\htdocs\hello-world\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\TaskController->index()
#4 C:\xampp\htdocs\hello-world\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TaskController))
#5 C:\xampp\htdocs\hello-world\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\hello-world\public\index.php(44): CodeIgniter\CodeIgniter->run()
#7 {main}
ERROR - 2021-04-22 17:00:14 --> Error connecting to the database: Unknown database 'taskapp'
CRITICAL - 2021-04-22 17:00:14 --> Unable to connect to the database.
#0 C:\xampp\htdocs\hello-world\vendor\codeigniter4\framework\system\Database\BaseConnection.php(618): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\hello-world\app\Models\TaskModel.php(11): CodeIgniter\Database\BaseConnection->query('INSERT INTO tas...')
#2 C:\xampp\htdocs\hello-world\app\Controllers\TaskController.php(30): App\Models\TaskModel->addTask('learning MySQL', 'I need the data...', 'dsadsad')
#3 C:\xampp\htdocs\hello-world\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\TaskController->addTask()
#4 C:\xampp\htdocs\hello-world\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TaskController))
#5 C:\xampp\htdocs\hello-world\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\hello-world\public\index.php(44): CodeIgniter\CodeIgniter->run()
#7 {main}
ERROR - 2021-04-22 17:02:18 --> Error connecting to the database: Unknown database 'taskapp'
CRITICAL - 2021-04-22 17:02:18 --> Unable to connect to the database.
#0 C:\xampp\htdocs\hello-world\vendor\codeigniter4\framework\system\Database\BaseConnection.php(618): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\hello-world\app\Models\TaskModel.php(11): CodeIgniter\Database\BaseConnection->query('INSERT INTO tas...')
#2 C:\xampp\htdocs\hello-world\app\Controllers\TaskController.php(30): App\Models\TaskModel->addTask('learning MySQL', 'I need the data...', 'www.python.org')
#3 C:\xampp\htdocs\hello-world\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\TaskController->addTask()
#4 C:\xampp\htdocs\hello-world\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TaskController))
#5 C:\xampp\htdocs\hello-world\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\hello-world\public\index.php(44): CodeIgniter\CodeIgniter->run()
#7 {main}
